# Generated by Django 5.0.2 on 2024-02-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=50)),
                ('preco', models.IntegerField()),
            ],
        ),
    ]
